### ISSUE TITLE
Merging the two branches

### ISSUE THREAD

**Issue by RccCookie** [FRC-Team-3140/FRC2015Code#13]
Hey guys, i'm righting this because I'm running into a little bit of a problem, I cannot merge mainstream and upstream together, even though the conflicts are minor, I receive the dreaded "The user operation is waiting for background work to complete" when ever I try to save at all (after merging). So, if any of you know how to merge these two branches and or fix my problem (which is happening on two of my computers) then please let me know.

-Ryan

**Comment by RccCookie** [comment]
Also, as a side-note the code is still working on a local-level when it comes to running the robot, so worse case-scenario we still have the local copy of the autonomous code.

**Comment by iRandD** [comment]
Upstream and Mainstream have so many simple yet different merge conflicts that we have made the executive decision to refrain from merging the two branches, as upstream has been proven to work and works well, rather than risk an error that could cost us valuable time in the upcoming two days, and also the lack of time to test to ensure that a merged code would work, we have decided to leave upstream be.
